### PR TITLE
Sectioned index with columns

### PR DESCRIPTION
**Pull request by Artoria2e5**
The hope is that people spend less time scrolling through .3pm

### CODE REVIEW

**Comment by keith** [comment]
nice! something like this sounds good, but it seems like this doesn't work as is?

**Comment by Artoria2e5** [comment]
Well, time for me to clone the repo and see what blew up!

**Comment by Artoria2e5** [comment]
Got it to work: the problem was in the rm fail. Also added a table of contents and did some basic styling
.

**Comment by keith** [comment]
thanks!

**Pull request merged**
